version: "3.8"
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    container_name: celery_worker
    depends_on:
      - redis
    volumes:
      - .:/app
    restart: always
    command: celery -A tasks worker --loglevel=info

  celery_beat:
    build: .
    container_name: celery_beat
    depends_on:
      - redis
    volumes:
      - .:/app
    restart: always
    command: celery -A tasks beat --loglevel=info
