# Generated by Django 5.1.4 on 2024-12-17 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeDealCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_car', models.CharField(max_length=255, unique=True)),
                ('url_car', models.CharField(max_length=255)),
                ('car_mark', models.CharField(blank=True, max_length=255, null=True)),
                ('car_model', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
                ('millage', models.CharField(blank=True, max_length=255, null=True)),
                ('images', models.TextField(blank=True, null=True)),
                ('main_image', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('transmission', models.CharField(blank=True, max_length=255, null=True)),
                ('engine_capacity', models.CharField(blank=True, max_length=255, null=True)),
                ('car_fuel', models.CharField(blank=True, max_length=255, null=True)),
                ('car_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'site_autohub_cars',
            },
        ),
        migrations.CreateModel(
            name='TimeDealCarBobaedream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_car', models.CharField(max_length=255)),
                ('url_car', models.URLField()),
                ('car_mark', models.CharField(max_length=255)),
                ('car_model', models.CharField(max_length=255)),
                ('drive', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=255)),
                ('millage', models.CharField(max_length=255)),
                ('images', models.TextField()),
                ('main_image', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('transmission', models.CharField(max_length=255)),
                ('engine_capacity', models.CharField(max_length=255)),
                ('car_fuel', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'site_bobaedream_cars',
            },
        ),
        migrations.CreateModel(
            name='TimeDealCarCharancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_car', models.CharField(max_length=255)),
                ('url_car', models.URLField(max_length=255)),
                ('car_mark', models.CharField(max_length=255)),
                ('car_model', models.CharField(max_length=255)),
                ('car_complectation', models.CharField(max_length=255)),
                ('car_type', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('millage', models.IntegerField()),
                ('images', models.TextField()),
                ('main_image', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('transmission', models.CharField(max_length=255)),
                ('engine_capacity', models.CharField(max_length=255)),
                ('car_fuel', models.CharField(max_length=255)),
                ('car_description', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'site_charancha_cars',
            },
        ),
        migrations.CreateModel(
            name='TimeDealCarKcar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_car', models.CharField(max_length=255)),
                ('url_car', models.URLField(max_length=255)),
                ('car_model', models.CharField(max_length=255)),
                ('car_mark', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('main_image', models.CharField(max_length=255)),
                ('images', models.TextField()),
                ('year', models.IntegerField()),
                ('millage', models.IntegerField()),
                ('drive', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('car_fuel', models.CharField(max_length=255)),
                ('transmission', models.CharField(max_length=255)),
                ('car_noAccident', models.CharField(max_length=255)),
                ('car_type', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'site_kcar_cars',
            },
        ),
        migrations.CreateModel(
            name='TimeDealCarMpark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_car', models.CharField(max_length=255)),
                ('url_car', models.URLField(max_length=255)),
                ('car_mark', models.CharField(max_length=255)),
                ('car_model', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('year', models.CharField(max_length=255)),
                ('millage', models.IntegerField()),
                ('car_fuel', models.CharField(max_length=255)),
                ('car_color', models.CharField(max_length=255)),
                ('car_noAccident', models.CharField(max_length=255)),
                ('engine_capacity', models.IntegerField()),
                ('car_type', models.CharField(max_length=255)),
                ('transmission', models.CharField(max_length=255)),
                ('main_image', models.CharField(max_length=255)),
                ('images', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'site_mpark_cars',
            },
        ),
    ]
